version: "3.8"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    environment:
      - ENV=dev
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
